version: "3"
services:
#----------------------------------------------------
  mysqldb:
    image: mysql
#    restart: always
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    networks:
      - project1
#-----------------------------------------------------      
  springbootapp:
    container_name: springboootapp
    build: .
    restart: on-failure:2
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
#    volumes:
#        -  I:/Satish/testdb:/var/lib/mysql
    networks:
      - project1
    depends_on:
      - mysqldb
networks:
  project1: