
create table if not exists customer (
       customer_number integer generated by default as identity,
        address_line1 varchar(255),
        address_line2 varchar(255),
        city varchar(255),
        country varchar(255),
        customer_first_name varchar(255),
        customer_last_name varchar(255),
        phone bigint,
        postal_code integer,
        state varchar(255),
        primary key (customer_number)
    );
    
    create table if not exists product (
       product_code integer generated by default as identity,
        price double,
        product_description varchar(255),
        product_name varchar(255),
        quantity_in_stock integer,
        primary key (product_code)
    );
    
     create if not exists orders (
       order_number integer generated by default as identity,
        comments varchar(255),
        customer_number integer,
        order_date timestamp,
        shipped_date timestamp,
        status varchar(255),
        primary key (order_number)
    );
    
    create table if not exists order_details (
       order_number integer generated by default as identity,
        price_each double,
        product_code integer,
        quantity_ordered integer,
        primary key (order_number)
    )
    
    